### ISSUE TITLE
maxRecordCount can be set to anything!

### ISSUE THREAD

**Issue by mjuniper** [koopjs/featureservice#25]
https://github.com/koopjs/featureservice/blob/master/index.js#L284

If I'm reading this right, we use `maxRecordCount` as the page size. However, though this is usually 1000 or 2000, customers can set it to anything.

We've got a customer right now whose downloads are failing. They have set `maxRecordCount` to 10000. I suspect (though I am not certain) that is the cause.

I think we should do something like: 

```
var size = (layer.maxRecordCount < 2001) ? layer.maxRecordCount : 2000
```

**Comment by mjuniper** [comment]
I think I'll PR this change because I think this is a sensible change even if it is not the cause of my issue.

**Comment by dmfenton** [comment]
We have a check that sets the maximum max record count to 5000 or whatever is passed in with options.
See here: 
https://github.com/mjuniper/featureservice/blob/max-record-count/index.js#L38
https://github.com/mjuniper/featureservice/blob/max-record-count/index.js#L312
