### ISSUE TITLE
Add a LICENSE file and text for Apache

### ISSUE THREAD

**Issue by ajturner** [koopjs/featureservice#3]

**Comment by ungoldman** [comment]
forked to https://github.com/koopjs/featureservice so we can continue working on it while @chelm is away

**Comment by chelm** [comment]
@ngoldman shall we just move it there? or do you want to be a collaborators here?

**Comment by chelm** [comment]
added @ngoldman and @dmfenton as collaborators here...

**Comment by ungoldman** [comment]
Thanks @chelm. If you're okay with moving it to koopjs that would simplify things. We already moved @dmfenton's fork there, but can move yours over and get changes from his fork back into your upstream.

**Comment by chelm** [comment]
@ngoldman agree. How best to navigate this? Do you want delete the fork before I move it? I created a PR back here so the changes get brought in. Just not sure what comes first or if it matters.

**Comment by ungoldman** [comment]
I guess that works.
1. merge `koopjs/featureservice` into `chelm/featureservice`
2. delete `koopjs/featureservice`
3. move `chelm/featureservice` to `koopjs`
4. call it a day

@chelm sound good?

**Comment by chelm** [comment]
Yup.

**Comment by ungoldman** [comment]
Yay! Thanks @chelm.

**Comment by chelm** [comment]
@ngoldman k Im out. this is done
